-- ---------------------------------------------------------------------------------------
-- Insert: pareto.context_property_type. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pareto.i_context_property_type(
  IN id_context UUID, 
  IN id_schema UUID, 
  IN id_generic_property_type UUID, 
  IN length INTEGER, 
  IN scale INTEGER, 
  IN is_nullable BOOLEAN, 
  IN default_value TEXT, 
  IN created_by VARCHAR
)
RETURNS pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'i_context_property_type';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     pareto.pg_val;  
  v_response     pareto.pg_resp;

  v_updated_at   TIMESTAMPTZ;

  -- Set the Property Variables
  v_id_context UUID := id_context;
  v_id_schema UUID := id_schema;
  v_id UUID := NULL;
  v_created_by VARCHAR := created_by;
  v_is_nullable BOOLEAN := is_nullable;
  v_length INTEGER := length;
  v_id_generic_property_type UUID := id_generic_property_type;
  v_scale INTEGER := scale;
  v_default_value TEXT := default_value;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id_context', id_context, 
    'id_schema', id_schema, 
    'id_generic_property_type', id_generic_property_type, 
    'length', length, 
    'scale', scale, 
    'is_nullable', is_nullable, 
    'default_value', default_value, 
    'created_by', created_by
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------

  INSERT INTO pareto.context_property_type (
    id_context, 
    id_schema, 
    id_generic_property_type, 
    length, 
    scale, 
    is_nullable, 
    default_value, 
    created_by,
    updated_by
  )
  VALUES (
    v_id_context, 
    v_id_schema, 
    v_id_generic_property_type, 
    v_length, 
    v_scale, 
    v_is_nullable, 
    v_default_value, 
    v_created_by,
    v_created_by
  )
  RETURNING id, updated_at INTO v_id, v_updated_at;

  v_response := (
    'OK',
    jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
    NULL, 
    '00000',
    'Insert was successful', 
    NULL, 
    NULL
  );
  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN UNIQUE_VIOLATION THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        '23514', 
        'A UNIQUE constraint was violated due to duplicate data', 
        'A record already exists in the context_property_type table', 
        'Check the provided data and try again'
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_created_by, v_metadata);
      RETURN v_response;
  
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_created_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
