-- ---------------------------------------------------------------------------------------
-- Insert: pareto.generic_property_type. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pareto.i_generic_property_type(
  IN id_generic_data_type UUID, 
  IN id_tenant UUID, 
  IN id_validation UUID, 
  IN name VARCHAR, 
  IN description TEXT, 
  IN length INTEGER, 
  IN scale INTEGER, 
  IN is_nullable BOOLEAN, 
  IN default_value TEXT, 
  IN created_by VARCHAR
)
RETURNS pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'i_generic_property_type';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     pg_val;
  v_response     pg_resp;

  v_updated_at   TIMESTAMPTZ;

  -- Set the Property Variables
  v_name VARCHAR := name;
  v_id UUID := NULL;
  v_created_by VARCHAR := created_by;
  v_id_generic_data_type UUID := id_generic_data_type;
  v_id_validation UUID := id_validation;
  v_is_nullable BOOLEAN := is_nullable;
  v_description TEXT := description;
  v_length INTEGER := length;
  v_id_tenant UUID := id_tenant;
  v_scale INTEGER := scale;
  v_default_value TEXT := default_value;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'name', name, 
    'id', id, 
    'created_by', created_by, 
    'id_generic_data_type', id_generic_data_type, 
    'id_validation', id_validation, 
    'is_nullable', is_nullable, 
    'description', description, 
    'length', length, 
    'id_tenant', id_tenant, 
    'scale', scale, 
    'default_value', default_value
  );
  
  -- ------------------------------------------------------
  -- Validations
  -- ------------------------------------------------------
  
  v_val_resp := is_name('name', name);
  IF NOT v_val_resp.passed THEN
    v_errors := v_errors || jsonb_build_object('type', 'validation', 'field', v_val_resp.field, 'message', v_val_resp.message);
  END IF;

  IF jsonb_array_length(v_errors) > 0 THEN
    v_response := (
      'ERROR', 
      NULL, 
      v_errors, 
      '23514', 
      'A CHECK constraint was violated due to incorrect input', 
      'Ensure all fields in the ''errors'' array are correctly formatted', 
      'The provided data did not pass validation checks'
    );
    CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_created_by, v_metadata);
    RETURN v_response;
  END IF;
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------

  INSERT INTO pareto.generic_property_type (
    id_generic_data_type, 
    id_tenant, 
    id_validation, 
    name, 
    description, 
    length, 
    scale, 
    is_nullable, 
    default_value, 
    created_by,
    updated_by
  )
  VALUES (
    v_id_generic_data_type, 
    v_id_tenant, 
    v_id_validation, 
    v_name, 
    v_description, 
    v_length, 
    v_scale, 
    v_is_nullable, 
    v_default_value, 
    v_created_by,
    v_created_by
  )
  RETURNING id, updated_at INTO v_id, v_updated_at;

  v_response := (
    'OK',
    jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
    NULL, 
    '00000',
    'Insert was successful', 
    NULL, 
    NULL
  );
  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN UNIQUE_VIOLATION THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        '23514', 
        'A UNIQUE constraint was violated due to duplicate data', 
        'A record already exists in the generic_property_type table', 
        'Check the provided data and try again'
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_created_by, v_metadata);
      RETURN v_response;
  
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_created_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
