-- ---------------------------------------------------------------------------------------
-- Insert: pareto.project_component_omit. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------

DROP FUNCTION IF EXISTS pareto.i_project_component_omit;
CREATE FUNCTION pareto.i_project_component_omit(
  IN id_project_component UUID, 
  IN id_data_object UUID
)
RETURNS pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'i_project_component_omit';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     pareto.pg_val;  
  v_response     pareto.pg_resp;

  v_updated_at   TIMESTAMPTZ;

  -- Set the Property Variables
  v_id_project_component UUID := id_project_component;
  v_id_data_object UUID := id_data_object;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id_project_component', id_project_component, 
    'id_data_object', id_data_object
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------

  INSERT INTO pareto.project_component_omit (
    id_project_component, 
    id_data_object
  )
  VALUES (
    v_id_project_component, 
    v_id_data_object
  )
  RETURNING id_project_component, id_data_object INTO v_id_project_component, v_id_data_object;

  v_response := (
    'OK',
    jsonb_build_object('id_project_component', v_id_project_component, 'id_data_object', v_id_data_object), 
    NULL, 
    '00000',
    'Insert was successful', 
    NULL, 
    NULL
  );
  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN UNIQUE_VIOLATION THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', 'A UNIQUE constraint was violated due to duplicate data'), 
        '23514', 
        'A UNIQUE constraint was violated due to duplicate data', 
        'A record already exists in the project_component_omit table', 
        'Check the provided data and try again'
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, 'unknown', v_metadata);
      RETURN v_response;
  
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', SQLERRM), 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, 'unknown', v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
