-- ---------------------------------------------------------------------------------------
-- Insert: pareto.property. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pareto.i_property(
  IN id_data_object uuid, 
  IN id_generic_data_type uuid, 
  IN id_generic_property_type uuid, 
  IN id_validation uuid, 
  IN sequence Integer, 
  IN name varchar, 
  IN description text, 
  IN length Integer, 
  IN scale Integer, 
  IN is_nullable boolean, 
  IN default_value text, 
  IN created_by varchar
)
RETURNS pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'i_property';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     pg_val;
  v_response     pg_resp;

  v_id           UUID;
  v_updated_at   TIMESTAMPTZ;

  -- Set variables to avoid ambiguous column names
  v_id_data_object uuid := id_data_object;
  v_id_generic_data_type uuid := id_generic_data_type;
  v_id_generic_property_type uuid := id_generic_property_type;
  v_id_validation uuid := id_validation;
  v_sequence Integer := sequence;
  v_name varchar := name;
  v_description text := description;
  v_length Integer := length;
  v_scale Integer := scale;
  v_is_nullable boolean := is_nullable;
  v_default_value text := default_value;
  v_created_by varchar := created_by;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id_data_object', id_data_object, 
    'id_generic_data_type', id_generic_data_type, 
    'id_generic_property_type', id_generic_property_type, 
    'id_validation', id_validation, 
    'sequence', sequence, 
    'name', name, 
    'description', description, 
    'length', length, 
    'scale', scale, 
    'is_nullable', is_nullable, 
    'default_value', default_value, 
    'created_by', created_by
  );
  
  -- ------------------------------------------------------
  -- Validations
  -- ------------------------------------------------------
  
  v_val_resp := is_name('name', name);
  IF NOT v_val_resp.passed THEN
    v_errors := v_errors || jsonb_build_object('type', 'validation', 'field', v_val_resp.field, 'message', v_val_resp.message);
  END IF;

  IF jsonb_array_length(v_errors) > 0 THEN
    v_response := (
      'ERROR', 
      NULL, 
      v_errors, 
      '23514', 
      'A CHECK constraint was violated due to incorrect input', 
      'Ensure all fields in the ''errors'' array are correctly formatted', 
      'The provided data did not pass validation checks'
    );
    CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, created_by, v_metadata);
    RETURN v_response;
  END IF;
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------

  INSERT INTO pareto.property (
    id_data_object, 
    id_generic_data_type, 
    id_generic_property_type, 
    id_validation, 
    sequence, 
    name, 
    description, 
    length, 
    scale, 
    is_nullable, 
    default_value, 
    created_by,
    updated_by
  )
  VALUES (
    v_id_data_object, 
    v_id_generic_data_type, 
    v_id_generic_property_type, 
    v_id_validation, 
    v_sequence, 
    v_name, 
    v_description, 
    v_length, 
    v_scale, 
    v_is_nullable, 
    v_default_value, 
    v_created_by,
    v_created_by
  )
  RETURNING id, updated_at INTO v_id, v_updated_at;  

  v_response := (
    'OK', 
    jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
    NULL, 
    '00000',
    'Insert was successful', 
    NULL, 
    NULL
  );
  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN UNIQUE_VIOLATION THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        '23514', 
        'A UNIQUE constraint was violated due to duplicate data', 
        'A record already exists in the property table', 
        'Check the provided data and try again'
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, created_by, v_metadata);
      RETURN v_response;
  
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, created_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
