-- -----------------------------------------------------------------------------
-- Table: pareto.property. Generated by Pareto Factory™ "Be Consistent"
-- -----------------------------------------------------------------------------
CREATE TABLE pareto.property (
  id                               UUID             NOT NULL  DEFAULT GEN_RANDOM_UUID(), 
  id_data_object                   UUID             NOT NULL,
  id_generic_data_type             UUID             NOT NULL,
  id_generic_property_type         UUID,
  id_validation                    UUID, 
  sequence                         INT              NOT NULL, 
  name                             VARCHAR(32)      NOT NULL  CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  description                      TEXT, 
  length                           INT, 
  precision                        INT, 
  is_nullable                      BOOLEAN          NOT NULL  DEFAULT FALSE, 
  default_value                    TEXT, 
  created_at                       TIMESTAMP        NOT NULL  DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL  DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL  DEFAULT TRUE
);

ALTER TABLE pareto.property ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX property_alt_key 
    ON pareto.property(id_data_object, LOWER(name));

ALTER TABLE pareto.property
  ADD CONSTRAINT property_data_object
  FOREIGN KEY (id_data_object)
  REFERENCES pareto.data_object(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON pareto.property 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();