-- ---------------------------------------------------------------------------------------
-- Update: pareto.context_property_type. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pareto.u_context_property_type(
  IN id UUID, 
  IN id_context UUID, 
  IN id_schema UUID, 
  IN id_generic_property_type UUID, 
  IN length INTEGER, 
  IN scale INTEGER, 
  IN is_nullable BOOLEAN, 
  IN default_value TEXT, 
  IN updated_at TIMESTAMPTZ, 
  IN updated_by VARCHAR
)
RETURNS pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'u_context_property_type';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     pg_val;
  v_response     pg_resp;

  v_updates      INT;
  v_message      TEXT;
  v_count        INT;

  -- Set the Property Variables
  v_id_context UUID := id_context;
  v_id_schema UUID := id_schema;
  v_id UUID := id;
  v_updated_at TIMESTAMPTZ := updated_at;
  v_is_nullable BOOLEAN := is_nullable;
  v_length INTEGER := length;
  v_updated_by VARCHAR := updated_by;
  v_id_generic_property_type UUID := id_generic_property_type;
  v_scale INTEGER := scale;
  v_default_value TEXT := default_value;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id_context', id_context, 
    'id_schema', id_schema, 
    'id', id, 
    'updated_at', updated_at, 
    'is_nullable', is_nullable, 
    'length', length, 
    'updated_by', updated_by, 
    'id_generic_property_type', id_generic_property_type, 
    'scale', scale, 
    'default_value', default_value
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------

  UPDATE pareto.context_property_type SET
    id_context = v_id_context, 
    id_schema = v_id_schema, 
    id_generic_property_type = v_id_generic_property_type, 
    length = v_length, 
    scale = v_scale, 
    is_nullable = v_is_nullable, 
    default_value = v_default_value, 
    updated_by = v_updated_by, 
    updated_at = CURRENT_TIMESTAMP
    WHERE id = v_id
      AND updated_at = v_updated_at
    RETURNING id, updated_at INTO v_id, v_updated_at;
  
  GET DIAGNOSTICS v_updates = ROW_COUNT;

  IF v_updates > 0 THEN
    -- Record was updated
    v_response := (
      'OK', 
      jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
      NULL, 
      '00000',
      'Update was successful', 
      NULL, 
      NULL
  );    
  ELSE  
    -- Check for Optimistic Lock Error
    v_id := id;
    SELECT count(*) INTO v_count   
      FROM pareto.context_property_type 
    WHERE id = v_id;
          
    IF (v_count > 0) THEN
      -- Record does exists but the updated_at timestamp has changed
      -- The id and updated_at values are not returned. The client must refresh the record.      
      v_message := 'The record was updated by another transaction. Refresh and try again';
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'optimistic_lock', 'field', 'updated_at', 'message', v_message), 
        '00002',
        'No records were found matching the query.',
        'The UPDATED_AT query parameter does not match the current record.',
        'Obtain the latest updated_at timestamp and try again.'          
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_updated_by, v_metadata);
      RETURN v_response;
    ELSE
      -- Record does not exist
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        '00002',
        'No records were found matching the query.',
        'Check the query parameters or ensure data exists.',
        'The requested resource does not exist in the database.'          
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_updated_by, v_metadata);
    END IF;
 END IF;    

  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_updated_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
