-- ---------------------------------------------------------------------------------------
-- Update: pareto.context_property_type. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP FUNCTION IF EXISTS pareto.u_context_property_type;
CREATE FUNCTION pareto.u_context_property_type(
  IN p_id UUID, 
  IN p_id_context UUID, 
  IN p_id_schema UUID, 
  IN p_id_generic_property_type UUID, 
  IN p_length INTEGER, 
  IN p_scale INTEGER, 
  IN p_is_nullable BOOLEAN, 
  IN p_default_value TEXT, 
  IN p_updated_at TIMESTAMP, 
  IN p_updated_by VARCHAR
)
RETURNS pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'u_context_property_type';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     pareto.pg_val;
  v_response     pareto.pg_resp;

  v_updates      INT;
  v_message      TEXT;
  v_count        INT;
  v_updated_at   TIMESTAMP := p_updated_at;
  
  -- Primary Key Field(s)
  v_id uuid := p_id;
  
BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id', p_id, 
    'id_context', p_id_context, 
    'id_schema', p_id_schema, 
    'id_generic_property_type', p_id_generic_property_type, 
    'length', p_length, 
    'scale', p_scale, 
    'is_nullable', p_is_nullable, 
    'default_value', p_default_value, 
    'updated_at', p_updated_at, 
    'updated_by', p_updated_by
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------

  UPDATE pareto.context_property_type SET
    id_context = p_id_context, 
    id_schema = p_id_schema, 
    id_generic_property_type = p_id_generic_property_type, 
    length = p_length, 
    scale = p_scale, 
    is_nullable = p_is_nullable, 
    default_value = p_default_value, 
    updated_by = p_updated_by, 
    updated_at = CURRENT_TIMESTAMP
    WHERE id = p_id
      AND DATE_TRUNC('second', updated_at) = DATE_TRUNC('second', p_updated_at)
    RETURNING id, updated_at INTO v_id, v_updated_at;
  
  GET DIAGNOSTICS v_updates = ROW_COUNT;

  IF v_updates > 0 THEN
    -- Record was updated
    v_response := (
      'OK', 
      jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
      NULL, 
      '00000',
      'Update was successful', 
      NULL, 
      NULL
  );    
  ELSE  
    -- Check for Optimistic Lock Error
    SELECT count(*) INTO v_count   
      FROM pareto.context_property_type 
    WHERE id = v_id;
          
    IF (v_count > 0) THEN
      -- Record does exists but the updated_at timestamp has changed
      -- The id and updated_at values are not returned. The client must refresh the record.      
      v_message := 'The record was updated by another transaction. Refresh and try again';
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'optimistic_lock', 'field', 'updated_at', 'message', v_message), 
        '00002',
        'No records were found matching the query.',
        'The UPDATED_AT query parameter does not match the current record.',
        'Obtain the latest updated_at timestamp and try again.'          
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, p_updated_by, v_metadata);
      RETURN v_response;
    ELSE
      -- Record does not exist
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        '00002',
        'No records were found matching the query.',
        'Check the query parameters or ensure data exists.',
        'The requested resource does not exist in the database.'          
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, p_updated_by, v_metadata);
    END IF;
 END IF;    

  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, p_updated_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
