-- ---------------------------------------------------------------------------------------
-- Insert: pareto.index_property. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pareto.i_index_property(
  IN id uuid, 
  IN id_index uuid, 
  IN id_property uuid, 
  IN id_rt_sort_order uuid, 
  IN sequence Integer, 
  IN created_at timestamptz, 
  IN created_by varchar, 
  IN updated_at timestamptz, 
  IN updated_by varchar, 
  IN is_active boolean
)
RETURNS pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'i_index_property';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     pg_val;
  v_response     pg_resp;

  v_id           UUID;
  v_updated_at   TIMESTAMPTZ;

  -- Set variables to avoid ambiguous column names
  v_id uuid := id;
  v_id_index uuid := id_index;
  v_id_property uuid := id_property;
  v_id_rt_sort_order uuid := id_rt_sort_order;
  v_sequence Integer := sequence;
  v_created_at timestamptz := created_at;
  v_created_by varchar := created_by;
  v_updated_at timestamptz := updated_at;
  v_updated_by varchar := updated_by;
  v_is_active boolean := is_active;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id', id, 
    'id_index', id_index, 
    'id_property', id_property, 
    'id_rt_sort_order', id_rt_sort_order, 
    'sequence', sequence, 
    'created_at', created_at, 
    'created_by', created_by, 
    'updated_at', updated_at, 
    'updated_by', updated_by, 
    'is_active', is_active
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------

  INSERT INTO pareto.index_property (
    id, 
    id_index, 
    id_property, 
    id_rt_sort_order, 
    sequence, 
    created_at, 
    updated_at, 
    updated_by, 
    is_active, 
    created_by,
    updated_by
  )
  VALUES (
    v_id, 
    v_id_index, 
    v_id_property, 
    v_id_rt_sort_order, 
    v_sequence, 
    v_created_at, 
    v_updated_at, 
    v_updated_by, 
    v_is_active, 
    v_created_by,
    v_created_by
  )
  RETURNING index_property.id, index_property.updated_at INTO v_id, v_updated_at;  

  v_response := (
    'OK', 
    jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
    NULL, 
    '00000',
    'Insert was successful', 
    NULL, 
    NULL
  );
  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN UNIQUE_VIOLATION THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        '23514', 
        'A UNIQUE constraint was violated due to duplicate data', 
        'A record already exists in the index_property table', 
        'Check the provided data and try again'
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, created_by, v_metadata);
      RETURN v_response;
  
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, created_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
