-- ---------------------------------------------------------------------------------------
-- Update: pareto.property. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pareto.u_property(
  IN id UUID, 
  IN id_data_object UUID, 
  IN id_generic_data_type UUID, 
  IN id_generic_property_type UUID, 
  IN id_validation UUID, 
  IN sequence INTEGER, 
  IN name VARCHAR, 
  IN description TEXT, 
  IN length INTEGER, 
  IN scale INTEGER, 
  IN is_nullable BOOLEAN, 
  IN default_value TEXT, 
  IN updated_at TIMESTAMPTZ, 
  IN updated_by VARCHAR
)
RETURNS pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'u_property';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     pareto.pg_val;
  v_response     pareto.pg_resp;

  v_updates      INT;
  v_message      TEXT;
  v_count        INT;

  -- Set the Property Variables
  v_id UUID := id;
  v_updated_at TIMESTAMPTZ := updated_at;
  v_length INTEGER := length;
  v_updated_by VARCHAR := updated_by;
  v_id_generic_property_type UUID := id_generic_property_type;
  v_default_value TEXT := default_value;
  v_name VARCHAR := name;
  v_id_generic_data_type UUID := id_generic_data_type;
  v_sequence INTEGER := sequence;
  v_id_data_object UUID := id_data_object;
  v_id_validation UUID := id_validation;
  v_is_nullable BOOLEAN := is_nullable;
  v_description TEXT := description;
  v_scale INTEGER := scale;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id', id, 
    'updated_at', updated_at, 
    'length', length, 
    'updated_by', updated_by, 
    'id_generic_property_type', id_generic_property_type, 
    'default_value', default_value, 
    'name', name, 
    'id_generic_data_type', id_generic_data_type, 
    'sequence', sequence, 
    'id_data_object', id_data_object, 
    'id_validation', id_validation, 
    'is_nullable', is_nullable, 
    'description', description, 
    'scale', scale
  );
  
  -- ------------------------------------------------------
  -- Validations
  -- ------------------------------------------------------
  
  v_val_resp := is_name('name', name);
  IF NOT v_val_resp.passed THEN
    v_errors := v_errors || jsonb_build_object('type', 'validation', 'field', v_val_resp.field, 'message', v_val_resp.message);
  END IF;

  IF jsonb_array_length(v_errors) > 0 THEN
    v_response := (
      'ERROR', 
      NULL, 
      v_errors, 
      '23514', 
      'A CHECK constraint was violated due to incorrect input', 
      'Ensure all fields in the ''errors'' array are correctly formatted', 
      'The provided data did not pass validation checks'
    );
    CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_created_by, v_metadata);
    RETURN v_response;
  END IF;
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------

  UPDATE pareto.property SET
    id_data_object = v_id_data_object, 
    id_generic_data_type = v_id_generic_data_type, 
    id_generic_property_type = v_id_generic_property_type, 
    id_validation = v_id_validation, 
    sequence = v_sequence, 
    name = v_name, 
    description = v_description, 
    length = v_length, 
    scale = v_scale, 
    is_nullable = v_is_nullable, 
    default_value = v_default_value, 
    updated_by = v_updated_by, 
    updated_at = CURRENT_TIMESTAMP
    WHERE id = v_id
      AND updated_at = v_updated_at
    RETURNING id, updated_at INTO v_id, v_updated_at;
  
  GET DIAGNOSTICS v_updates = ROW_COUNT;

  IF v_updates > 0 THEN
    -- Record was updated
    v_response := (
      'OK', 
      jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
      NULL, 
      '00000',
      'Update was successful', 
      NULL, 
      NULL
  );    
  ELSE  
    -- Check for Optimistic Lock Error
    v_id := id;
    SELECT count(*) INTO v_count   
      FROM pareto.property 
    WHERE id = v_id;
          
    IF (v_count > 0) THEN
      -- Record does exists but the updated_at timestamp has changed
      -- The id and updated_at values are not returned. The client must refresh the record.      
      v_message := 'The record was updated by another transaction. Refresh and try again';
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'optimistic_lock', 'field', 'updated_at', 'message', v_message), 
        '00002',
        'No records were found matching the query.',
        'The UPDATED_AT query parameter does not match the current record.',
        'Obtain the latest updated_at timestamp and try again.'          
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_updated_by, v_metadata);
      RETURN v_response;
    ELSE
      -- Record does not exist
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        '00002',
        'No records were found matching the query.',
        'Check the query parameters or ensure data exists.',
        'The requested resource does not exist in the database.'          
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_updated_by, v_metadata);
    END IF;
 END IF;    

  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL pareto.i_logs(v_response.status, v_response.message, c_service_name, v_updated_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
