-- ---------------------------------------------------------------------------------------
-- Table: pareto.context_data_type. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS pareto.context_data_type CASCADE;

CREATE TABLE pareto.context_data_type (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_tenant                        UUID             NOT NULL, 
  id_context                       UUID             NOT NULL, 
  id_generic_data_type             UUID             NOT NULL, 
  sequence                         INTEGER          NOT NULL, 
  name                             VARCHAR(32)      NOT NULL, 
  description                      TEXT             NULL, 
  alias                            TEXT             NOT NULL, 
  context_value                    TEXT             NOT NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE pareto.context_data_type ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX context_data_type_alt_key
    ON pareto.context_data_type(id_tenant, id_context, id_generic_data_type);

ALTER TABLE pareto.context_data_type
  ADD CONSTRAINT context_data_type_id_tenant
  FOREIGN KEY (id_tenant)
  REFERENCES pareto.tenant(id)
  ON DELETE CASCADE;
    
ALTER TABLE pareto.context_data_type
  ADD CONSTRAINT context_data_type_id_context
  FOREIGN KEY (id_context)
  REFERENCES pareto.context(id)
  ON DELETE CASCADE;
    
ALTER TABLE pareto.context_data_type
  ADD CONSTRAINT context_data_type_id_generic_data_type
  FOREIGN KEY (id_generic_data_type)
  REFERENCES pareto.generic_data_type(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON pareto.context_data_type 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

ALTER TABLE pareto.context_data_type ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON pareto.context_data_type
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
