-- ---------------------------------------------------------------------------------------
-- Table: pareto.context_data_type. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS pareto.context_data_type CASCADE;

CREATE TABLE pareto.context_data_type (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_context                       UUID             NOT NULL, 
  id_generic_data_type             UUID             NOT NULL, 
  sequence                         INTEGER          NOT NULL, 
  name                             VARCHAR(32)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  description                      TEXT             NULL, 
  alias                            TEXT             NOT NULL, 
  context_value                    TEXT             NOT NULL, 
  created_at                       TIMESTAMPTZ      NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMPTZ      NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE pareto.context_data_type ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX context_data_type_alt_key
    ON pareto.context_data_type(id_context, LOWER(name));

ALTER TABLE pareto.context_data_type
  ADD CONSTRAINT context_data_type_id_context
  FOREIGN KEY (id_context)
  REFERENCES pareto.context(id)
  ON DELETE CASCADE;
    
ALTER TABLE pareto.context_data_type
  ADD CONSTRAINT context_data_type_id_generic_data_type
  FOREIGN KEY (id_generic_data_type)
  REFERENCES pareto.generic_data_type(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON pareto.context_data_type 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();
