-- ---------------------------------------------------------------------------------------
-- Table: pareto.data_object. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS pareto.data_object CASCADE;

CREATE TABLE pareto.data_object (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_schema                        UUID             NOT NULL, 
  name                             VARCHAR(32)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  description                      TEXT             NULL, 
  has_identifier                   BOOLEAN          NOT NULL    DEFAULT TRUE, 
  has_audit                        BOOLEAN          NOT NULL    DEFAULT TRUE, 
  has_active                       BOOLEAN          NOT NULL    DEFAULT TRUE, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE pareto.data_object ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX data_object_alt_key
    ON pareto.data_object(id_schema, LOWER(name));

ALTER TABLE pareto.data_object
  ADD CONSTRAINT data_object_id_schema
  FOREIGN KEY (id_schema)
  REFERENCES pareto.schema(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON pareto.data_object 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();
