-- ---------------------------------------------------------------------------------------
-- Table: pareto.generic_property_type. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS pareto.generic_property_type CASCADE;

CREATE TABLE pareto.generic_property_type (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_generic_data_type             UUID             NOT NULL, 
  id_validation                    UUID             NULL, 
  name                             VARCHAR(32)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  description                      TEXT             NULL, 
  length                           INTEGER          NULL, 
  scale                            INTEGER          NULL, 
  is_nullable                      BOOLEAN          NOT NULL, 
  default_value                    TEXT             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE pareto.generic_property_type ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX generic_property_type_alt_key
    ON pareto.generic_property_type(LOWER(name));

ALTER TABLE pareto.generic_property_type
  ADD CONSTRAINT generic_property_type_id_generic_data_type
  FOREIGN KEY (id_generic_data_type)
  REFERENCES pareto.generic_data_type(id)
  ON DELETE CASCADE;
    
ALTER TABLE pareto.generic_property_type
  ADD CONSTRAINT generic_property_type_id_validation
  FOREIGN KEY (id_validation)
  REFERENCES pareto.validation(id)
  ON DELETE SET NULL;

CREATE TRIGGER update_at
  BEFORE UPDATE ON pareto.generic_property_type 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();
