-- ---------------------------------------------------------------------------------------
-- Table: pareto.plugin. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS pareto.plugin CASCADE;

CREATE TABLE pareto.plugin (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_context                       UUID             NOT NULL, 
  name                             VARCHAR(32)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  description                      TEXT             NULL, 
  plugin_service                   TEXT             NOT NULL    CHECK (plugin_service ~ '^[a-z][a-zA-Z0-9_]*$'), 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE pareto.plugin ADD PRIMARY KEY (id);

CREATE INDEX plugin_alt_key
    ON pareto.plugin(id_context, LOWER(name));

ALTER TABLE pareto.plugin
  ADD CONSTRAINT plugin_id_context
  FOREIGN KEY (id_context)
  REFERENCES pareto.context(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON pareto.plugin 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();
