-- ---------------------------------------------------------------------------------------
-- Table: pareto.project. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS pareto.project CASCADE;

CREATE TABLE pareto.project (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_schema                        UUID             NOT NULL, 
  name                             VARCHAR(32)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  description                      TEXT             NULL, 
  domain                           VARCHAR(32)      NOT NULL    CHECK (domain ~ '^[a-z0-9]+(\.[a-z0-9]+)*$'), 
  artifact                         VARCHAR(32)      NOT NULL    CHECK (artifact ~ '^[a-z0-9]+(\.[a-z0-9]+)*$'), 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE pareto.project ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX project_alt_key
    ON pareto.project(id_schema, LOWER(name));

ALTER TABLE pareto.project
  ADD CONSTRAINT project_id_schema
  FOREIGN KEY (id_schema)
  REFERENCES pareto.schema(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON pareto.project 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();
