-- ---------------------------------------------------------------------------------------
-- Table: pareto.project_component_property. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS pareto.project_component_property CASCADE;

CREATE TABLE pareto.project_component_property (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_project_component             UUID             NOT NULL, 
  sequence                         INTEGER          NOT NULL, 
  data_object_filter               TEXT             NOT NULL, 
  property_filter                  TEXT             NOT NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE pareto.project_component_property ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX project_component_property_alt_key
    ON pareto.project_component_property(id_project_component, LOWER(data_object_filter), LOWER(property_filter));

ALTER TABLE pareto.project_component_property
  ADD CONSTRAINT project_component_property_id_project_component
  FOREIGN KEY (id_project_component)
  REFERENCES pareto.project_component(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON pareto.project_component_property 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();
